### ISSUE TITLE
Demo question

### ISSUE THREAD

**Issue by argyleink** [kenchris/dual-screen-demos#1]
this feels like a UX engineer's attempt at showing what the UX should be, is that the goal?

**Comment by kenchris** [comment]
Not entirely. Microsoft engineers stated that their goal was for web devs to easily adopt web content to a single viewport spanning two screens with potential seam (metal henge) in the middle as well as keyboard popping up on each side.

The keyboard by default (no user change) would change the whole viewport size - thus move up all content, which means a weird experience on the screen not showing a keyboard.

They wanted a JS API that devs would hook into, but I think a CSS API (say env()) would be easier to use, hence the demo which emulates that using CSS Custom Properties
